### ISSUE TITLE
Add plausible & google analytics options to site

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenotejs#132]
```yaml
site:
  analytics:
     - type: plausible
       domain: something.curve.space
     - type: google-analytics
       code: GA-123456-U
```
